### ISSUE TITLE
Practica 1 Comparación de 2 aplicaciones realidad virtual y realidad aumentada

### ISSUE THREAD

**Issue by Francisco536** [SistemasTecTlaxiaco/aplicacion-con-realidad-aumentada-Francisco536#3]
Reporte 1
[Practica1_Francisco.pdf](https://github.com/SistemasTecTlaxiaco/aplicacion-con-realidad-aumentada-Francisco536/files/6133935/Practica1_Francisco.pdf)

**Comment by ArteezyOne** [comment]
Calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
